sudo: true
language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get install libx11-dev libxrandr-dev libasound2-dev libgl1-mesa-dev
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
#  - sudo pip install codecov # From https://github.com/travis-ci/travis-ci/issues/1705
  - sudo apt-get update -qq

#install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

addons:
  apt:
    packages:
    - libboost-all-dev

script: 
 - cd ..
 - git clone https://github.com/richelbilderbeek/RibiClasses
 - git clone https://github.com/richelbilderbeek/RibiLibraries
 - ls
 - cd RibiLibraries
 - ./Urho3d.sh
 - cd ..
 - cd RosindellEtAl2008
 - qmake RosindellEtAl2008Console.pro
 - make
 - qmake RosindellEtAl2008Desktop.pro
 - make
 - qmake RosindellEtAl2008Desktop3d.pro
 - make

after_success:
  - codecov