sudo: required
language: cpp
compiler: gcc

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # C++14
  - sudo apt-get install -qq g++-5
  # Urho3D
  - sudo apt-get install libx11-dev libxrandr-dev libasound2-dev libgl1-mesa-dev
  - sudo apt-get install libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev
  - ./build_urho3d
  # 
  - ./download_other_githubs

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libboost1.55-all-dev

script: 
  # Console
  - qmake RosindellEtAl2008Console.pro
  - make
  - ./RosindellEtAl2008Console &
  - sleep 10
  - sudo killall RosindellEtAl2008Console
  # Desktop
  - qmake RosindellEtAl2008Desktop.pro
  - make
  - ./RosindellEtAl2008Desktop &
  - sleep 10
  - sudo killall RosindellEtAl2008Desktop
  # Desktop 3D
  - qmake RosindellEtAl2008Desktop3d.pro
  - make
  - ./RosindellEtAl2008Desktop3d &
  - sleep 10
  - sudo killall RosindellEtAl2008Desktop3d
