#!/bin/sh

# Build the Urho3D library in a local folder

if [ ! -d Urho3D ]
then
  # The original one
  #git clone https://github.com/Urho3D/Urho3D

  # Modified slightly by richelbilderbeek
  git clone https://github.com/richelbilderbeek/Urho3D
fi

cd Urho3D 
cmake .
make
./cmake_generic.sh
cd Source
cd ThirdParty
cd Bullet
make

ln -s ./Urho3D/bin/Data
ln -s ./Urho3D/bin/CoreData